# -*- coding: utf-8 -*-
"""Assignment_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NtuMzODjzqIcq0GfBfJJHNYR5imAaYtT
"""

import numpy as np
import random as rd
import math

size_siml = 1000000
x_zero_y_zero = x_one_y_zero = 0
#binary possibilities
bin_poss = np.array([0,1])
for i in range(size_siml):
  x = np.random.choice(bin_poss, p=[0.2, 0.8])
  if x == 0 :
    y = np.random.choice(bin_poss, p=[0.857143, 0.142857])
    if y == 0 : 
      x_zero_y_zero += 1
  if x == 1 : 
    y = np.random.choice(bin_poss, p=[0.142857, 0.857143])
    if y == 0 : 
      x_one_y_zero += 1

prob_x_one_y_zero = (x_one_y_zero/(x_zero_y_zero+x_one_y_zero))
print(f"The result obtained from simulation is : {prob_x_one_y_zero}")
print(f"The result obtained theoretically is : 0.4")
diff_var_diff = prob_x_one_y_zero - 0.4
print(f"The difference between the simulations' and the theoretical values are : {diff_var_diff}")